# Generated by Django 2.1.3 on 2018-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181129_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('delete_yn', models.CharField(default='n', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='delete_yn',
            field=models.CharField(default='n', max_length=3),
        ),
    ]
